/** Major Ivorian cities/communes, used for the city picker at registration. */
export const CI_CITIES = [
  "Abidjan",
  "Bouaké",
  "Daloa",
  "Yamoussoukro",
  "San-Pédro",
  "Korhogo",
  "Man",
  "Divo",
  "Gagnoa",
  "Anyama",
  "Agboville",
  "Grand-Bassam",
  "Bingerville",
  "Abengourou",
  "Séguéla",
  "Odienné",
  "Bondoukou",
  "Ferkessédougou",
  "Issia",
  "Sinfra",
  "Soubré",
  "Dabou",
  "Dimbokro",
  "Aboisso",
  "Tiassalé",
  "Adzopé",
] as const;
