/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as LoginRouteImport } from './routes/login'
import { Route as TabsRouteImport } from './routes/_tabs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TabsProfileRouteImport } from './routes/_tabs.profile'
import { Route as TabsPaymentsRouteImport } from './routes/_tabs.payments'
import { Route as TabsMissionsRouteImport } from './routes/_tabs.missions'
import { Route as TabsHomeRouteImport } from './routes/_tabs.home'
import { Route as TabsPaymentsIndexRouteImport } from './routes/_tabs.payments.index'
import { Route as TabsMissionsIndexRouteImport } from './routes/_tabs.missions.index'
import { Route as TabsPaymentsIdRouteImport } from './routes/_tabs.payments.$id'
import { Route as TabsMissionsIdRouteImport } from './routes/_tabs.missions.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsRoute = TabsRouteImport.update({
  id: '/_tabs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsProfileRoute = TabsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => TabsRoute,
} as any)
const TabsPaymentsRoute = TabsPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => TabsRoute,
} as any)
const TabsMissionsRoute = TabsMissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => TabsRoute,
} as any)
const TabsHomeRoute = TabsHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => TabsRoute,
} as any)
const TabsPaymentsIndexRoute = TabsPaymentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TabsPaymentsRoute,
} as any)
const TabsMissionsIndexRoute = TabsMissionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TabsMissionsRoute,
} as any)
const TabsPaymentsIdRoute = TabsPaymentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TabsPaymentsRoute,
} as any)
const TabsMissionsIdRoute = TabsMissionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TabsMissionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/home': typeof TabsHomeRoute
  '/missions': typeof TabsMissionsRouteWithChildren
  '/payments': typeof TabsPaymentsRouteWithChildren
  '/profile': typeof TabsProfileRoute
  '/missions/$id': typeof TabsMissionsIdRoute
  '/payments/$id': typeof TabsPaymentsIdRoute
  '/missions/': typeof TabsMissionsIndexRoute
  '/payments/': typeof TabsPaymentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/home': typeof TabsHomeRoute
  '/profile': typeof TabsProfileRoute
  '/missions/$id': typeof TabsMissionsIdRoute
  '/payments/$id': typeof TabsPaymentsIdRoute
  '/missions': typeof TabsMissionsIndexRoute
  '/payments': typeof TabsPaymentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_tabs': typeof TabsRouteWithChildren
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_tabs/home': typeof TabsHomeRoute
  '/_tabs/missions': typeof TabsMissionsRouteWithChildren
  '/_tabs/payments': typeof TabsPaymentsRouteWithChildren
  '/_tabs/profile': typeof TabsProfileRoute
  '/_tabs/missions/$id': typeof TabsMissionsIdRoute
  '/_tabs/payments/$id': typeof TabsPaymentsIdRoute
  '/_tabs/missions/': typeof TabsMissionsIndexRoute
  '/_tabs/payments/': typeof TabsPaymentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pending'
    | '/register'
    | '/sitemap.xml'
    | '/home'
    | '/missions'
    | '/payments'
    | '/profile'
    | '/missions/$id'
    | '/payments/$id'
    | '/missions/'
    | '/payments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pending'
    | '/register'
    | '/sitemap.xml'
    | '/home'
    | '/profile'
    | '/missions/$id'
    | '/payments/$id'
    | '/missions'
    | '/payments'
  id:
    | '__root__'
    | '/'
    | '/_tabs'
    | '/login'
    | '/pending'
    | '/register'
    | '/sitemap.xml'
    | '/_tabs/home'
    | '/_tabs/missions'
    | '/_tabs/payments'
    | '/_tabs/profile'
    | '/_tabs/missions/$id'
    | '/_tabs/payments/$id'
    | '/_tabs/missions/'
    | '/_tabs/payments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TabsRoute: typeof TabsRouteWithChildren
  LoginRoute: typeof LoginRoute
  PendingRoute: typeof PendingRoute
  RegisterRoute: typeof RegisterRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs': {
      id: '/_tabs'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs/profile': {
      id: '/_tabs/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof TabsProfileRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/payments': {
      id: '/_tabs/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof TabsPaymentsRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/missions': {
      id: '/_tabs/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof TabsMissionsRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/home': {
      id: '/_tabs/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof TabsHomeRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/payments/': {
      id: '/_tabs/payments/'
      path: '/'
      fullPath: '/payments/'
      preLoaderRoute: typeof TabsPaymentsIndexRouteImport
      parentRoute: typeof TabsPaymentsRoute
    }
    '/_tabs/missions/': {
      id: '/_tabs/missions/'
      path: '/'
      fullPath: '/missions/'
      preLoaderRoute: typeof TabsMissionsIndexRouteImport
      parentRoute: typeof TabsMissionsRoute
    }
    '/_tabs/payments/$id': {
      id: '/_tabs/payments/$id'
      path: '/$id'
      fullPath: '/payments/$id'
      preLoaderRoute: typeof TabsPaymentsIdRouteImport
      parentRoute: typeof TabsPaymentsRoute
    }
    '/_tabs/missions/$id': {
      id: '/_tabs/missions/$id'
      path: '/$id'
      fullPath: '/missions/$id'
      preLoaderRoute: typeof TabsMissionsIdRouteImport
      parentRoute: typeof TabsMissionsRoute
    }
  }
}

interface TabsMissionsRouteChildren {
  TabsMissionsIdRoute: typeof TabsMissionsIdRoute
  TabsMissionsIndexRoute: typeof TabsMissionsIndexRoute
}

const TabsMissionsRouteChildren: TabsMissionsRouteChildren = {
  TabsMissionsIdRoute: TabsMissionsIdRoute,
  TabsMissionsIndexRoute: TabsMissionsIndexRoute,
}

const TabsMissionsRouteWithChildren = TabsMissionsRoute._addFileChildren(
  TabsMissionsRouteChildren,
)

interface TabsPaymentsRouteChildren {
  TabsPaymentsIdRoute: typeof TabsPaymentsIdRoute
  TabsPaymentsIndexRoute: typeof TabsPaymentsIndexRoute
}

const TabsPaymentsRouteChildren: TabsPaymentsRouteChildren = {
  TabsPaymentsIdRoute: TabsPaymentsIdRoute,
  TabsPaymentsIndexRoute: TabsPaymentsIndexRoute,
}

const TabsPaymentsRouteWithChildren = TabsPaymentsRoute._addFileChildren(
  TabsPaymentsRouteChildren,
)

interface TabsRouteChildren {
  TabsHomeRoute: typeof TabsHomeRoute
  TabsMissionsRoute: typeof TabsMissionsRouteWithChildren
  TabsPaymentsRoute: typeof TabsPaymentsRouteWithChildren
  TabsProfileRoute: typeof TabsProfileRoute
}

const TabsRouteChildren: TabsRouteChildren = {
  TabsHomeRoute: TabsHomeRoute,
  TabsMissionsRoute: TabsMissionsRouteWithChildren,
  TabsPaymentsRoute: TabsPaymentsRouteWithChildren,
  TabsProfileRoute: TabsProfileRoute,
}

const TabsRouteWithChildren = TabsRoute._addFileChildren(TabsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TabsRoute: TabsRouteWithChildren,
  LoginRoute: LoginRoute,
  PendingRoute: PendingRoute,
  RegisterRoute: RegisterRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
